//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasketballApp_2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BasketbollEntities : DbContext
    {
        public BasketbollEntities()
            : base("name=BasketbollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnthropologicalData> AnthropologicalData { get; set; }
        public virtual DbSet<Club> Club { get; set; }
        public virtual DbSet<Competition> Competition { get; set; }
        public virtual DbSet<Hall> Hall { get; set; }
        public virtual DbSet<MemberHistory> MemberHistory { get; set; }
        public virtual DbSet<Participant> Participant { get; set; }
        public virtual DbSet<Sponsor> Sponsor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Town> Town { get; set; }
        public virtual DbSet<Trainer> Trainer { get; set; }
        public virtual DbSet<TypesOfTransport> TypesOfTransport { get; set; }
    }
}
