//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasketballApp_2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public int CompetitionID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<int> ClubID { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Team Team { get; set; }
    }
}
