//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasketballApp_2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberHistory
    {
        public int MemberHistoryID { get; set; }
        public string Rank { get; set; }
        public string Amplua { get; set; }
        public Nullable<int> GameNumber { get; set; }
        public Nullable<int> AnthropologicalDataID { get; set; }
        public Nullable<int> ParticipantID { get; set; }
    
        public virtual AnthropologicalData AnthropologicalData { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
